export { default as Linkedin } from './linkedin'
export { default as GitHub } from './github'
export { default as File } from './file'
export { default as Info } from './info'
export { default as Instagram } from './instagram'
